### ISSUE TITLE
Python version requirements

### ISSUE THREAD

**Issue by alexandervlpl** [AdrianVollmer/htun#5]
Thanks for this interesting project! I'm unable to install the requirements on Python 3.9.2. It looks like `pytun` is outdated.

Are both `pytun` AND `python_pytun` required? Which Python version does this work on?

```
Collecting pytun==1.0.1 (from -r requirements.txt (line 4))
  Using cached pytun-1.0.1.tar.gz (2.7 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-s9p63j6z/pytun_4e9e7dc47b7f4cf0b0c11ea57391a6a0/setup.py", line 11, in <module>
          import pytun
        File "/tmp/pip-install-s9p63j6z/pytun_4e9e7dc47b7f4cf0b0c11ea57391a6a0/pytun.py", line 115
          except IOError, e:
                        ^
      SyntaxError: invalid syntax
      [end of output]
```

**Comment by AdrianVollmer** [comment]
Looks like I put that line there accidentally. It's not needed, `python-pytun` is what is actually used. Thanks for the feedback!
